apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-role
rules:
  - apiGroups:
      - networking.k8s.io/v1
    resources:
      - NetworkPolicy
    verbs:
      - create
      - delete
      - list
      - get
      - update
  - apiGroups:
      - security.istio.io/v1beta1
    resources:
      - PeerAuthentication
    verbs:
      - create
      - delete
      - list
      - get
      - update
